#######################################################
## This file holds all the REST related properties
#######################################################

rest.endpoints.jsonplaceholder.url=https://jsonplaceholder.typicode.com
#rest.endpoints.singsys.url=
rest.endpoints.singsys.url=${SYNGSIS_HOST:http://localhost}/SignsysAPI
#rest.endpoints.singsys.app.id=
rest.endpoints.singsys.app.id=fglosas
#rest.endpoints.singsys.app.version=
rest.endpoints.singsys.app.version=string
#rest.endpoints.singsys.username=
rest.endpoints.singsys.username=${SYNGSIS_USER}
#rest.endpoints.singsys.password=
rest.endpoints.singsys.password=${SYNGSIS_PASSWORD}

rest.endpoints.templates.engine.url=https://ms-util-motor-plantillas.cross-utilidades.meshgw-qa.ocilabscl.bancodechile.cl
#rest.endpoints.templates.engine.url=svc-ms-util-motor-plantillas.cross-utilidades.svc.cluster.local